database:
  ConnectionStrings:
    default: "Server=216.105.171.178; Database=s523_liebtest; Port=3306; User=u523_pXX90m5ZgE; Password=Ur78BQEGnFfE!eYb8S6@L@wD;"

Stats:
  Message: "[Stats for {PlayerName} #{Position}]\n Kills: {Kills} Deaths: {Deaths} Headshots: {Headshots} KDR: {Kdr:F2} Accuracy: {Accuracy:F2}%\n Messages: {Messages} Zombies: {Zombies} Megas: {MegaZombies}\nFish: {Fish} Animals: {Animals} Harvests: {Harvests} Resources: {Resources}"
Ranking:
  SortBy: "Kills"
  Header: "[Top 10 Kills]"
  Message: "\n#{Position} {PlayerName} | Kills: {Kills} Deaths: {Deaths} Headshots: {Headshots} KDR: {Kdr:F2} Accuracy: {Accuracy:F2}%"

